// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfeoqbkymcnlyomlvkiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZW9xYmt5bWNubHlvbWx2a2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTgwNTcsImV4cCI6MjA2NDgzNDA1N30.7cfDNMQLB3gtQG3ESkUbZWp4ed6LhHHTyk3hruqD3jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);