// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrwoehblutxpitdiuilk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyd29laGJsdXR4cGl0ZGl1aWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjY1MjQsImV4cCI6MjA2NDgwMjUyNH0.86je_0n6dq3WaKItTVFaxbuq-OgCOWVL2etDCOGdYNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);